{% set name = "sirocco" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/miguelmarco/SIROCCO2/releases/download/{{ version }}/libsirocco-{{ version }}.tar.gz
  sha256: 83d1dd5622120eda42c475696235dd67be8072a76baad0a70693d9743a659a61

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("sirocco") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - gnuconfig  # [unix]
  host:
    - gmp
    - mpfr
  run:

test:
  commands:
    - test -f $PREFIX/include/sirocco.h
    - test -f $PREFIX/lib/libsirocco${SHLIB_EXT}

about:
  home: https://github.com/miguelmarco/SIROCCO2
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: sirocco port to C++ and MPFR
  dev_url: https://github.com/miguelmarco/libbraiding
  description: This is a library for computing homotopy continuation ...

extra:
  recipe-maintainers:
    - enriqueartal
    - isuruf
