schema_version: 1

context:
  name: sirocco
  version: "2.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/miguelmarco/SIROCCO2/releases/download/${{ version }}/libsirocco-${{ version }}.tar.gz
  sha256: 83d1dd5622120eda42c475696235dd67be8072a76baad0a70693d9743a659a61

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - if: unix
      then: gnuconfig
  host:
    - gmp
    - mpfr
  run_exports:
    - ${{ pin_subpackage("sirocco") }}

tests:
  - script:
      - test -f $PREFIX/include/sirocco.h
      - test -f $PREFIX/lib/libsirocco${SHLIB_EXT}

about:
  license: GPL-3.0-only
  license_file: LICENSE
  summary: sirocco port to C++ and MPFR
  description: This is a library for computing homotopy continuation ...
  homepage: https://github.com/miguelmarco/SIROCCO2
  repository: https://github.com/miguelmarco/libbraiding

extra:
  recipe-maintainers:
    - enriqueartal
    - isuruf
    - saraedum
